### ISSUE TITLE
DNS routing efficiency

### ISSUE THREAD

**Issue by zp-j** [cedexis/openmixapplib#31]
Hi,

I saw this description and tried some templates that enable overrides,

> These Openmix Application scripts are used by specialized DNS servers to respond to DNS requests based on the logic in the scripts.

Does this mean each DNS query will call the JavaScript function? Is there any performance issue as we would like the DNS to be as fast as possible? @mccdn

```javascript
function onRequest(request, response) {
    'use strict';
    handler.handle_request(request, response);
}
```

Thanks,
Zhipeng

**Comment by zp-j** [comment]
@mccdn

**Comment by jasonturner** [comment]
Correct this is executed on our DNS architecture on each DNS call. There are no performance issues we have seen with this (this is a custom build DNS so not anything like BIND or alike), with call execution occurring in microseconds.

**Comment by zp-j** [comment]
Thanks @jasonturner!
